### ISSUE TITLE
Edge case of right(var_0, var_0)

### ISSUE THREAD

**Issue by moqingyan** [csmith49/dragoman#1] opened 2019-08-30 20:31 UTC
```
{"scene": {"image_index": 0, "objects": [{"color": "blue", "size": "large", "rotation": 269.8517172617167, "shape": "cube", "3d_coords": [-1.3705521821975708, 2.0794010162353516, 0.699999988079071], "material": "rubber", "pixel_coords": [269, 88, 12.661545753479004]}, {"color": "green", "size": "large", "rotation": 292.2219458666971, "shape": "cylinder", "3d_coords": [-2.9289753437042236, -1.7488206624984741, 0.699999988079071], "material": "metal", "pixel_coords": [93, 108, 11.522202491760254]}, {"color": "cyan", "size": "small", "rotation": 25.545135239473026, "shape": "cube", "3d_coords": [1.5515961647033691, 0.6776641607284546, 0.3499999940395355], "material": "rubber", "pixel_coords": [319, 162, 10.045343399047852]}, {"color": "brown", "size": "large", "rotation": 327.3489188814305, "shape": "cylinder", "3d_coords": [-0.25301405787467957, -2.3089325428009033, 0.699999988079071], "material": "metal", "pixel_coords": [132, 159, 9.392304420471191]}, {"color": "gray", "size": "small", "rotation": 6.325183772442613, "shape": "cube", "3d_coords": [1.018894076347351, -1.93693208694458, 0.3499999940395355], "material": "rubber", "pixel_coords": [192, 197, 8.907766342163086]}, {"color": "brown", "size": "large", "rotation": 25.96049348342493, "shape": "sphere", "3d_coords": [0.43993687629699707, 2.9987525939941406, 0.699999988079071], "material": "metal", "pixel_coords": [353, 100, 11.964213371276855]}], "relationships": {"right": [[2, 5], [0, 2, 3, 4, 5], [5], [0, 2, 4, 5], [0, 2, 5], []], "behind": [[], [0, 5], [0, 1, 5], [0, 1, 2, 5], [0, 1, 2, 3, 5], [0]], "front": [[1, 2, 3, 4, 5], [2, 3, 4], [3, 4], [4], [], [1, 2, 3, 4]], "left": [[1, 3, 4], [], [0, 1, 3, 4], [1], [1, 3], [0, 1, 2, 3, 4]]}, "image_filename": "CLEVR_train_000000.png", "split": "train", "directions": {"right": [0.6563112735748291, 0.7544902563095093, -0.0], "behind": [-0.754490315914154, 0.6563112735748291, 0.0], "above": [0.0, 0.0, 1.0], "below": [-0.0, -0.0, -1.0], "left": [-0.6563112735748291, -0.7544902563095093, 0.0], "front": [0.754490315914154, -0.6563112735748291, -0.0]}}, "clause": [{"kind": "relate", "relation": "right", "left": "var_0", "right": "var_0"}]}
```

Here is an a edge case that I think the interpreter should handle as no option is available, since one object cannot be at itself's right position. However, the result I got is 
```
var_0
5
2
0
5
4
2
0
5
5
4
3
2
0
5
2
```

Can you help me take a look?
Thank you!

**Comment by csmith49** [comment] 2019-08-30 22:10
The problem is due in part to how tables are constructed from conjuncts. Previously, a relation `right(x, x)` would cause every tuple `<i, j>` in the `right` relation to generate a row `x,x; i,j;`, which was leading to the incorrect result. There's now a filter on table construction that checks if the relation variables are the same and proceeds appropriately.

Now there's a new bug - instead of returning the CSV containing just the header `var_0`, the above snippet produces a blank file. I'm working on a fix for that.

**Comment by csmith49** [comment] 2019-08-30 22:21
The problem is now fixed. The above produces the output `var_0`, and is included in the repo as `examples/problem3.json`.

**Closed as completed by csmith49** 2019-08-30 22:21 UTC
